CREATE TABLE TASKS(
   ID          INT       NOT NULL PRIMARY KEY,  
   NAME        CHAR(100) NOT NULL,
   DESCRIPTION CHAR(500),
   CREATEDDATE DATE,
   UPDATEDDATE DATE,
   CREATEDBY   CHAR(50),
   UPDATEDBY   CHAR(50)
);
